### ISSUE TITLE
What if we need Serial Number but don't use StageNow

### ISSUE THREAD

**Issue by mjbedford2017** [darryncampbell/EMDK-DeviceIdentifiers-Sample#1]
Hello, 

Our app that runs on the Zebra devices needs to access the serial number for support tracking via our app. As of lately, this has broken and we are just getting "unknown" as the serial number. Upon further research, I understand why we are getting "unknown" and am research how to get around it, which lead me to this article. 

However, we do not use StageNow to prep and deploy devices. Is there a way to still get the serial number and set whatever needs to be set without using StageNow?

Thanks!

**Comment by darryncampbell** [comment]
Hi, how do you deploy devices?  Do you use an EMM?

**Comment by darryncampbell** [comment]
Please also see my new post on this topic: https://developer.savanna.zebra.com/blog/device-identifiers-zebra-devices-running-android-10-%E2%80%93-complete-guide
